
# module5_visualization/run.py -- CLI entry point for generating figures
import sys, os, argparse
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def main():
    parser = argparse.ArgumentParser(description='Generate visualization figures')
    parser.add_argument('--module', type=str, default='all',
                       choices=['all', 'baseline', 'error', 'trajectory', 'comparison'])
    parser.add_argument('--dataset', type=str, default='all')
    parser.add_argument('--output_dir', type=str, default='results/visualizations')
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    print('Module 5 visualization: figures are generated by standalone scripts.')
    print('See results/visualizations/ for pre-generated figures.')
    print('To regenerate: run the viz generation scripts in module4_experiments.')

if __name__ == '__main__':
    main()
